# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/plataforma_educativa}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# Neo4j
neo4j.uri=${NEO4J_URI:bolt://localhost:7687}
neo4j.username=${NEO4J_USER:neo4j}
neo4j.password=${NEO4J_PASSWORD:password}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# App
spring.application.name=poliglota
server.port=8080